version: "3.9"

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  web:
    build: .
    restart: always
    environment:
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "5000:5000"
    depends_on:
      - mongo
#antonio