version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/TMDB_posters
    depends_on:
      - mongo
    volumes:
      - .:/app
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=TMDB_posters

volumes:
  mongo_data:
